### PR TITLE
Issue a comment rather than modifying the pull request description.

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by b-long** [comment]
@jimhester This looks great as a fix for #3.  I'm happy to accept the merge request.  In doing so, I'll deploy this as well (and update the README.md to include deployment instructions).  As far as I can tell, the current version is up-to-date (master is deployed to production):
```
ubuntu@cloud:~/prbot$ git log --pretty=oneline --abbrev-commit -n 1 --color
10708eb amend message with info for maintainers
```
Deployment should be as simple as git pull, then bouncing the process (it's not daemonized at the moment).  Any objections, speak before lunch :smile: .

cc/ @vobencha @dtenenba

**Comment by dtenenba** [comment]
Yes, first find the 'shotgun' process then kill it, then in the ~ubuntu/app directory:

    nohup shotgun -o 0.0.0.0 -p 9454 app.rb > prbot.log 2>&1 &

**Comment by b-long** [comment]
Ok, thanks @dtenenba .  I'll update this in production now.

**Comment by b-long** [comment]
Great work everybody, closing #3 as I can confirm this is fixed.  See here for example : https://github.com/Bioconductor-mirror/AnnotationHubData/pull/1

**Comment by jimhester** [comment]
:+1:

**Comment by dtenenba** [comment]
Thanks you guys!

**Pull request merged**
